---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: silverblue
description: This is my personal OS image base on Ublue Fedora Silverblue

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: akmods
    base: main
    install: []
    nvidia-driver: nvidia-open

  #- type: kargs
  #  arch: x86_64
  #  kargs:
     # - rd.driver.blacklist=nouveau
     # - modprobe.blacklist=nouveau 
     # - nvidia-drm.modeset=1
  
  - type: dnf
    repos:
      files:
        - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-software
        - gnome-initial-setup
        - gnome-tour
        - gnome-classic-session
        - gnome-user-docs
        - gnome-remote-desktop
        - transmission-daemon
    install:
      packages:
        - bat
        - btop
        - chezmoi
        - chromium
        - fastfetch
        - fuse-libs
        - git
        - libvirt
        - libvirt-client
        - libvirt-daemon
        - libvirt-daemon-driver-qemu
        - libvirt-daemon-config-network
        - lsd
        - kitty
        - mangohud
        - mullvad-vpn
        - neovim
        - qemu-kvm
        - signal-desktop
        - sshfs
        - starship
        - steam
        - vim
        - virt-install
        - virt-manager
        - zsh
  
  - type: default-flatpaks
    configurations:
    - scope: user
      repo:
        title: Flathub (user)
    - scope: system
      notify: false 
      repo:
        title: Flathub (system)
      install: 
          - com.github.IsmaelMartinez.teams_for_linux
          - com.github.johnfactotum.Foliate
          - com.github.tchx84.Flatseal
          - com.heroicgameslauncher.hgl
          - com.mattjakeman.ExtensionManager
          - com.rtosta.zapzap
          - com.vscodium.codium
          - com.vysp3r.ProtonPlus
          - com.saivert.pwvucontrol
          - dev.vencord.Vesktop
          - info.mumble.Mumble
          - io.github.celluloid_player.Celluloid
          - io.github.Foldex.AdwSteamGtk
          - io.github.kolunmi.Bazaar
          - io.missioncenter.MissionCenter
          - org.gnome.baobab
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.clocks
          - org.gnome.Contacts
          - org.gnome.Firmware
          - org.gnome.font-viewer
          - org.gnome.Logs
          - org.gnome.Loupe
          - org.gnome.NautilusPreviewer
          - org.gnome.Papers
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnucash.GnuCash
          - org.jellyfin.JellyfinDesktop
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
          - org.mozilla.thunderbird
          - org.remmina.Remmina
          - page.tesk.Refine

  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
      - Just Perfection
      - User Themes

  - type: initramfs
  - type: signing
